version: '3.4'

services:
  qbdlgui:
    image: ghcr.io/danieljcroberts/qbdlgui-reborn-multiurl:latest
    container_name: qbdlgui
    ports:
      - 5000:5000
    volumes:
      - /your/download/path:/downloads
      - qbdlgui-config:/config
    restart: unless-stopped

volumes:
  qbdlgui-config:
